server:
  servlet:
    context-path: /pps/api/kobbo
spring:
  application:
    name: kobbo
  datasource:
    url: jdbc:mysql://localhost:3306/kobbo?createDatabaseIfNotExist=true
    username: root
    password: ${PASSWORD_DB}
  jpa:
    show-sql: true