server:
  servlet:
    context-path: /api/v1/kobbo
spring:
  application:
    name: kobbo
  datasource:
    url: jdbc:mysql://localhost:3306/kobbo?createDatabaseIfNotExist=true
    username: root
    password: ${PASSWORD_DB}
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15min
    refreshTokenExpiration: 604800 # 7 jours